
services:
  db:
    image: postgis/postgis:16-master
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 80 --reload --log-config log_config.json
    volumes:
      - .:/code
      - ./temp/:/tmp/
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      - ".env"

# sudo docker-compose up --build
